#!/usr/bin/env bash

main () {
	local package="$1"
	local repo=~/repos/"$package"
	if [ -d $repo ]; then
		cd "$repo" && git fetch && git pull || return 1
	else
		git clone "https://aur.archlinux.org/$package.git" "$repo" && cd "$repo" || {
			[ -d "$repo" ] && rm -r "$repo"
			return 1
		}
	fi
	${EDITOR:-vim} PKGBUILD && makepkg -fsic
	cd - &> /dev/null
}

for i in "$@"; do
	main "$i"
done
