#!/usr/bin/env bash

main () {
	local package="$1"
	local repo=~/repos/"$package"
	if [ -d $repo ]; then
		cd "$repo" && git fetch && git pull || return 1
		${EDITOR:-vim} PKGBUILD &&
			makepkg -fsic ||
			return
	else
		curl --output /dev/null --silent --head --fail "https://aur.archlinux.org/packages/$package" &&
			git clone "https://aur.archlinux.org/$package.git" "$repo" && 
			cd "$repo" &&
			${EDITOR:-vim} PKGBUILD &&
			makepkg -fsic ||
			return

	fi
}

for i in "$@"; do
	( main "$i" )
done
